server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
token:
  secret: dXNlclRva2VuVGVzdHdkd2Vkd2Vkd2Vkd2Vkd3NkYXNkc2Fkd3FlcXdlcXdkcXdkcXdkcXdkcXdkcXdkcXd3ZWZzZGY=


spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            # /user-service/(?<segment>.*) 로 들어오면 /$\{segment} 로 변경시켜버리겠다.
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            # /user-service/(?<segment>.*) 로 들어오면 /$\{segment} 로 변경시켜버리겠다.
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            # /user-service/(?<segment>.*) 로 들어오면 /$\{segment} 로 변경시켜버리겠다.
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            # /user-service/(?<segment>.*) 로 들어오면 /$\{segment} 로 변경시켜버리겠다.
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace

