server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:\\\D:\git\spring-msa\git-repository
          uri: https://github.com/devSeok/spring-cloud-config.git
        default-label: master

#          uri: file:///${user.home}/git-repository

